# Generated by Django 4.2 on 2024-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KetoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
