# Generated by Django 4.2 on 2024-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0002_ketoarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
