# Generated by Django 4.2 on 2024-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0003_recipe_dish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
